export const testAccount01 = {
  firstName: "Rachel",
  lastName: "Nurmi",
  trips: [
    {
      id: 1,
      destination: "Japan",
      departure: "02/01/2926",
      hotels: [
        {
          hotelName: "Temple House by Curio",
          arrivalDate: "02/10/2026",
          departureDate: "02/15/2026",
          city: "Okinawa",
          country: "Japan",
          hotelConfirmation: "03432432432",
          nameOnReservation: "Rachel Nurmi",
        },
        {
          hotelName: "Hilton Tokyo",
          arrivalDate: "02/02/2026",
          departureDate: "02/10/2026",
          city: "Tokyo",
          country: "Japan",
          hotelConfirmation: "03432432432",
          nameOnReservation: "Rachel Nurmi",
        },
      ],
      flights: [
        {
          airlineName: "Air Tokyo",
          airportName: "Bradley International Airport",
          flightNumber: "ZM2913",
          flightDate: "02/01/2026",
          ticketHolderName: "Rachel Nurmi",
          confirmationNumber: "0293X2",
          seatAssignment: "23C",
        },
        {
          airlineName: "Air Tokyo",
          airportName: "Bradley International Airport",
          flightNumber: "ZM2913",
          flightDate: "02/01/2026",
          ticketHolderName: "Rachel Nurmi",
          confirmationNumber: "0293X2",
          seatAssignment: "23C",
        },
        {
          airlineName: "Air Tokyo",
          airportName: "Bradley International Airport",
          flightNumber: "ZM2913",
          flightDate: "02/01/2026",
          ticketHolderName: "Rachel Nurmi",
          confirmationNumber: "0293X2",
          seatAssignment: "23C",
        },
      ],
    },
  ],
};
