export const testAccount01 = {
  firstName: "Rachel",
  lastName: "Nurmi",
  username: "snurmi2",
  email: "stephnurmi@gmail.com",
  password: "123",
  trips: [
    {
      id: 1312324,
      tripName: "Japan",
      departureDate: "02/01/2026",
      hotels: [
        {
          hotelName: "Temple House by Curio",
          arrivalDate: "02/10/2026",
          departureDate: "02/15/2026",
          city: "Okinawa",
          country: "Japan",
          hotelConfirmation: "03432432432",
          nameOnReservation: "Rachel Nurmi",
        },
        {
          hotelName: "Hilton Tokyo",
          arrivalDate: "02/02/2026",
          departureDate: "02/10/2026",
          city: "Tokyo",
          country: "Japan",
          hotelConfirmation: "03432432432",
          nameOnReservation: "Rachel Nurmi",
        },
      ],
      flights: [
        {
          type: "roundtrip",
          airlineName1: "Air Tokyo",
          airportName1: "New York",
          flightNumber1: "ZM2913",
          flightDate1: "02/01/2026",
          confirmationNumber1: "0293X2",
          seatAssignment1: "12D",
          airlineName2: "Emirates",
          airportName2: "Tokyo",
          flightNumber2: "PB2003",
          flightDate2: "02/21/2026",
          confirmationNumber2: "02CC42",
          seatAssignment2: "23C",
          ticketHolderName2: "Rachel Nurmi",
        },
        {
          type: "oneway",
          airlineName: "Air Tokyo",
          airportName: "Bradley International Airport",
          flightNumber: "ZM2913",
          flightDate: "02/01/2026",
          ticketHolderName: "Rachel Nurmi",
          confirmationNumber: "0293X2",
          seatAssignment: "23C",
        },
      ],
    },
    {
      id: 865756324,
      tripName: "Disney",
      departureDate: "02/01/2926",
      hotels: [
        {
          hotelName: "Hotel Disney",
          arrivalDate: "02/10/2026",
          departureDate: "02/15/2026",
          city: "Orlando",
          country: "Florida",
          hotelConfirmation: "03432432432",
          nameOnReservation: "Rachel Nurmi",
        },
      ],
      flights: [
        {
          airlineName: "Southwest",
          airportName: "Bradley International Airport",
          flightNumber: "ZM2913",
          flightDate: "02/01/2026",
          ticketHolderName: "Rachel Nurmi",
          confirmationNumber: "0293X2",
          seatAssignment: "2C",
        },
        {
          airlineName: "Southwest",
          airportName: "Orlando International Airport",
          flightNumber: "ZM2913",
          flightDate: "02/11/2026",
          ticketHolderName: "Rachel Nurmi",
          confirmationNumber: "0293X2",
          seatAssignment: "13F",
        },
      ],
    },
  ],
};
