export const testAccount01 = {
  id: "SN-171-11-79814",
  firstName: "Rachel",
  lastName: "Nurmi",
  username: "snurmi2",
  email: "stephnurmi@gmail.com",
  password: "123",
  trips: [
    {
      id: 1312324,
      tripName: "Japan",
      departureDate: "2024-08-02T00:25:16.000Z",
      hotels: [
        {
          hotelName: "Temple House by Curio",
          arrivalDate: "02/10/2026",
          departureDate: "02/15/2026",
          city: "Okinawa",
          country: "Japan",
          hotelConfirmation: "03432432432",
          nameOnReservation: "Rachel Nurmi",
        },
        {
          hotelName: "Hilton Tokyo",
          arrivalDate: "02/02/2026",
          departureDate: "02/10/2026",
          city: "Tokyo",
          country: "Japan",
          hotelConfirmation: "03432432432",
          nameOnReservation: "Rachel Nurmi",
        },
      ],
      flights: [
        {
          type: "roundtrip",
          airline: "Air Tokyo",
          confirmationNo: "X97ST90",
          departureFlight: {
            departureAirport: "Gimpo International Airport",
            departureAirportCode: "GMP",
            departureAirportCity: "Seoul",
            departureAirportCountry: "South Korea",
            departureFlightNo: "4342009",
            departureDate: "2024-08-11T00:26:58.000Z",
            departureSeat: "2C",
          },
          returnFlight: {
            returnAirport: "Tokyo International Airport",
            returnAirportCode: "HND",
            returnAirportCity: "Tokyo",
            returnAirportCountry: "Japan",
            returnFlightNo: "0129833",
            returnDate: "2024-11-02T00:26:58.000Z",
            returnSeat: "5A",
          },
          ticketHolderName: null,
        },
        {
          type: "oneway",
          airline: "American Airline",
          confirmationNo: "XDM07S",
          departureFlight: {
            departureAirport: "Gen E L Logan International Airport",
            departureAirportCode: "BOS",
            departureAirportCity: "Boston",
            departureAirportCountry: "United States",
            departureFlightNo: "6324009",
            departureDate: "2024-08-02T00:25:16.000Z",
            departureSeat: "3D",
          },
          returnFlight: {
            returnAirport: "Gimpo International Airport",
            returnAirportCode: "GMP",
            returnAirportCity: "Seoul",
            returnAirportCountry: "South Korea",
            returnFlightNo: null,
            returnDate: null,
            returnSeat: null,
          },
          ticketHolderName: null,
        },
      ],
    },
    {
      id: 865756324,
      tripName: "Disney",
      departureDate: "02/01/2926",
      hotels: [
        {
          hotelName: "Hotel Disney",
          arrivalDate: "02/10/2026",
          departureDate: "02/15/2026",
          city: "Orlando",
          country: "Florida",
          hotelConfirmation: "03432432432",
          nameOnReservation: "Rachel Nurmi",
        },
      ],
      flights: [
        {
          airlineName: "Southwest",
          airportName: "Bradley International Airport",
          flightNumber: "ZM2913",
          flightDate: "02/01/2026",
          ticketHolderName: "Rachel Nurmi",
          confirmationNumber: "0293X2",
          seatAssignment: "2C",
        },
        {
          airlineName: "Southwest",
          airportName: "Orlando International Airport",
          flightNumber: "ZM2913",
          flightDate: "02/11/2026",
          ticketHolderName: "Rachel Nurmi",
          confirmationNumber: "0293X2",
          seatAssignment: "13F",
        },
      ],
    },
  ],
};
